# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: sky # emerald, blue, cyan, green, indigo, purple, red, rose, sky, teal, and zinc

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "my-navbar"
    # blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    highlight_active_link: true
    logo:
      text: "Jing Liang"
      # filename: "logo.png"
    # button:
    #   enable: true
    #   text: "Get Started"
    #   url: "https://hugoblox.com/templates/"

# Site footer
footer:
  block: minimal
  enable: true
  copyright:
    notice: '© 2025 Jing Liang. This work is licensed under MIT'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Oct 11, 2025'
  time_format: '14:38 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true